language: node_js
node_js: lts/*

cache:
  npm: true
  directories:
  - $HOME/.pnpm-store/

before_install:
- curl -L https://unpkg.com/@pnpm/self-installer | node

install:
- pnpm i

after_install:
- echo $NODE_PATH
- export NODE_PATH=./node_modules

script:
- echo define more scripts..
- pnpm run build

script:
  - pnpm run code:scanner
